### ISSUE TITLE
Issue when running "npm i"

### ISSUE THREAD

**Issue by graphcon** [PierrickP/multicycles#44]
When I clone this repo and run `npm i` I get the following output:

    D:\Sources\Node.js\multicycles>npm i

    > multicycles@1.0.0-beta.1 prepare D:\Sources\Node.js\multicycles
    > npm run clean && npm run transpile

    > multicycles@1.0.0-beta.1 clean D:\Sources\Node.js\multicycles
    > rm -rf providers/*/lib

    > multicycles@1.0.0-beta.1 transpile D:\Sources\Node.js\multicycles
    > lerna exec --ignore '@multicycles/{api,front,developer}' -- babel src --optional runtime --out-dir lib --ignore "__tests__"

    lerna info version 2.5.1
    lerna info versioning independent
    lerna info ignore '@multicycles/{api,front,developer}'
    src doesn't exist
    lerna ERR! exec Errored while executing 'babel src --optional runtime --out-dir lib --ignore __tests__' in '@multicycles/developer'
    lerna ERR! execute callback with error
    lerna ERR! Error: Command failed: babel src --optional runtime --out-dir lib --ignore __tests__
    lerna ERR!     at Promise.all.then.arr (D:\Sources\Node.js\multicycles\node_modules\execa\index.js:236:11)
    lerna ERR!     at <anonymous>
    ReferenceError: Unknown plugin "transform-runtime" specified in "D:\\Sources\\Node.js\\multicycles\\front\\.babelrc" at 1, attempted to resolve relative to "D:\\Sources\\Node.js\\multicycles\\front"
        at D:\Sources\Node.js\multicycles\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17
        at Array.map (<anonymous>)
        at Function.normalisePlugins (D:\Sources\Node.js\multicycles\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
        at OptionManager.mergeOptions (D:\Sources\Node.js\multicycles\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
        at OptionManager.init (D:\Sources\Node.js\multicycles\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
        at File.initOptions (D:\Sources\Node.js\multicycles\node_modules\babel-core\lib\transformation\file\index.js:212:65)
        at new File (D:\Sources\Node.js\multicycles\node_modules\babel-core\lib\transformation\file\index.js:135:24)
        at Pipeline.transform (D:\Sources\Node.js\multicycles\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
        at transform (D:\Sources\Node.js\multicycles\node_modules\babel-cli\lib\babel\util.js:50:22)
        at Object.compile (D:\Sources\Node.js\multicycles\node_modules\babel-cli\lib\babel\util.js:59:12)
    lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
    lerna ERR! exec Errored while executing 'babel src --optional runtime --out-dir lib --ignore __tests__' in '@multicycles/front'
    Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
        at throwVersionError (D:\Sources\Node.js\multicycles\node_modules\@babel\helper-plugin-utils\lib\index.js:62:11)
        at Object.assertVersion (D:\Sources\Node.js\multicycles\node_modules\@babel\helper-plugin-utils\lib\index.js:11:11)
        at D:\Sources\Node.js\multicycles\node_modules\@babel\plugin-proposal-object-rest-spread\lib\index.js:15:7
        at D:\Sources\Node.js\multicycles\node_modules\@babel\helper-plugin-utils\lib\index.js:16:12
        at Function.memoisePluginContainer (D:\Sources\Node.js\multicycles\node_modules\babel-core\lib\transformation\file\options\option-manager.js:113:13)
        at Function.normalisePlugin (D:\Sources\Node.js\multicycles\node_modules\babel-core\lib\transformation\file\options\option-manager.js:146:32)
        at D:\Sources\Node.js\multicycles\node_modules\babel-core\lib\transformation\file\options\option-manager.js:184:30
        at Array.map (<anonymous>)
        at Function.normalisePlugins (D:\Sources\Node.js\multicycles\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
        at OptionManager.mergeOptions (D:\Sources\Node.js\multicycles\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
        at OptionManager.init (D:\Sources\Node.js\multicycles\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
        at File.initOptions (D:\Sources\Node.js\multicycles\node_modules\babel-core\lib\transformation\file\index.js:212:65)
        at new File (D:\Sources\Node.js\multicycles\node_modules\babel-core\lib\transformation\file\index.js:135:24)
        at Pipeline.transform (D:\Sources\Node.js\multicycles\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
        at transform (D:\Sources\Node.js\multicycles\node_modules\babel-cli\lib\babel\util.js:50:22)
        at Object.compile (D:\Sources\Node.js\multicycles\node_modules\babel-cli\lib\babel\util.js:59:12)
        at write (D:\Sources\Node.js\multicycles\node_modules\babel-cli\lib\babel\dir.js:21:21)
        at handleFile (D:\Sources\Node.js\multicycles\node_modules\babel-cli\lib\babel\dir.js:43:7)
        at D:\Sources\Node.js\multicycles\node_modules\babel-cli\lib\babel\dir.js:61:9
        at Array.forEach (<anonymous>)
        at handle (D:\Sources\Node.js\multicycles\node_modules\babel-cli\lib\babel\dir.js:59:29)
        at Array.forEach (<anonymous>)
        at module.exports (D:\Sources\Node.js\multicycles\node_modules\babel-cli\lib\babel\dir.js:69:15)
        at Object.<anonymous> (D:\Sources\Node.js\multicycles\node_modules\babel-cli\lib\babel\index.js:129:1)
        at Module._compile (internal/modules/cjs/loader.js:654:30)
    lerna ERR! exec Errored while executing 'babel src --optional runtime --out-dir lib --ignore __tests__' in '@multicycles/bird'
    Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
        at throwVersionError (D:\Sources\Node.js\multicycles\node_modules\@babel\helper-plugin-utils\lib\index.js:62:11)
        at Object.assertVersion (D:\Sources\Node.js\multicycles\node_modules\@babel\helper-plugin-utils\lib\index.js:11:11)
        at D:\Sources\Node.js\multicycles\node_modules\@babel\plugin-proposal-object-rest-spread\lib\index.js:15:7
        at D:\Sources\Node.js\multicycles\node_modules\@babel\helper-plugin-utils\lib\index.js:16:12
        at Function.memoisePluginContainer (D:\Sources\Node.js\multicycles\node_modules\babel-core\lib\transformation\file\options\option-manager.js:113:13)
        at Function.normalisePlugin (D:\Sources\Node.js\multicycles\node_modules\babel-core\lib\transformation\file\options\option-manager.js:146:32)
        at D:\Sources\Node.js\multicycles\node_modules\babel-core\lib\transformation\file\options\option-manager.js:184:30
        at Array.map (<anonymous>)
        at Function.normalisePlugins (D:\Sources\Node.js\multicycles\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
        at OptionManager.mergeOptions (D:\Sources\Node.js\multicycles\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
        at OptionManager.init (D:\Sources\Node.js\multicycles\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
        at File.initOptions (D:\Sources\Node.js\multicycles\node_modules\babel-core\lib\transformation\file\index.js:212:65)
        at new File (D:\Sources\Node.js\multicycles\node_modules\babel-core\lib\transformation\file\index.js:135:24)
        at Pipeline.transform (D:\Sources\Node.js\multicycles\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
        at transform (D:\Sources\Node.js\multicycles\node_modules\babel-cli\lib\babel\util.js:50:22)
        at Object.compile (D:\Sources\Node.js\multicycles\node_modules\babel-cli\lib\babel\util.js:59:12)
        at write (D:\Sources\Node.js\multicycles\node_modules\babel-cli\lib\babel\dir.js:21:21)
        at handleFile (D:\Sources\Node.js\multicycles\node_modules\babel-cli\lib\babel\dir.js:43:7)
        at D:\Sources\Node.js\multicycles\node_modules\babel-cli\lib\babel\dir.js:61:9
        at Array.forEach (<anonymous>)
        at handle (D:\Sources\Node.js\multicycles\node_modules\babel-cli\lib\babel\dir.js:59:29)
        at Array.forEach (<anonymous>)
        at module.exports (D:\Sources\Node.js\multicycles\node_modules\babel-cli\lib\babel\dir.js:69:15)
        at Object.<anonymous> (D:\Sources\Node.js\multicycles\node_modules\babel-cli\lib\babel\index.js:129:1)
        at Module._compile (internal/modules/cjs/loader.js:654:30)
    lerna ERR! exec Errored while executing 'babel src --optional runtime --out-dir lib --ignore __tests__' in '@multicycles/byke'
    (node:568) UnhandledPromiseRejectionWarning: Error: Command failed: babel src --optional runtime --out-dir lib --ignore __tests__
        at Promise.all.then.arr (D:\Sources\Node.js\multicycles\node_modules\execa\index.js:236:11)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:182:7)
    (node:568) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
    (node:568) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! multicycles@1.0.0-beta.1 transpile: `lerna exec --ignore '@multicycles/{api,front,developer}' -- babel src --optional runtime --out-dir lib --ignore "__tests__"`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the multicycles@1.0.0-beta.1 transpile script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     ...\npm-cache\_logs\2018-09-05T20_44_34_287Z-debug.log
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! multicycles@1.0.0-beta.1 prepare: `npm run clean && npm run transpile`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the multicycles@1.0.0-beta.1 prepare script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     ...\npm-cache\_logs\2018-09-05T20_44_34_329Z-debug.log`

**Comment by PierrickP** [comment]
just tried without error.
npm install probably failed, check with `npm ls` and re-install with `npm i`

**Comment by graphcon** [comment]
Hi @PierrickP,

thank you for your answer. Yes, `npm install` failed because, `npm i` failed (see headline of this issue).
Running `npm i` multiple times also didn't help.
My guess is, there is at least one package you have installed globally on your machine but that package isn't in in the projects `package.json`.

Here another log
```
> multicycles@1.0.0-beta.1 prepare D:\Sources\Node.js\multicycles
> npm run clean && npm run transpile


> multicycles@1.0.0-beta.1 clean D:\Sources\Node.js\multicycles
> rm -rf providers/*/lib


> multicycles@1.0.0-beta.1 transpile D:\Sources\Node.js\multicycles
> lerna exec --ignore '@multicycles/{api,front,developer}' -- babel src --optional runtime --out-dir lib --ignore "__tests__"

lerna info version 2.5.1
lerna info versioning independent
lerna info ignore '@multicycles/{api,front,developer}'
src doesn't exist
lerna ERR! exec Errored while executing 'babel src --optional runtime --out-dir lib --ignore __tests__' in '@multicycles/developer'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: babel src --optional runtime --out-dir lib --ignore __tests__
lerna ERR!     at Promise.all.then.arr (D:\Sources\Node.js\multicycles\node_modules\execa\index.js:236:11)
lerna ERR!     at <anonymous>
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
Error: Error: Plugin/Preset files are not allowed to export objects, only functions. In D:\Sources\Node.js\multicycles\front\node_modules\babel-preset-stage-2\lib\index.js
    at D:\Sources\Node.js\multicycles\node_modules\@babel\cli\lib\babel\dir.js:143:22
    at D:\Sources\Node.js\multicycles\node_modules\@babel\cli\lib\babel\dir.js:106:23
    at D:\Sources\Node.js\multicycles\node_modules\@babel\cli\lib\babel\dir.js:78:23
    at D:\Sources\Node.js\multicycles\node_modules\@babel\cli\lib\babel\dir.js:40:23
    at D:\Sources\Node.js\multicycles\node_modules\@babel\cli\lib\babel\util.js:76:16
    at D:\Sources\Node.js\multicycles\node_modules\@babel\core\lib\transform-file.js:39:14
    at process._tickCallback (internal/process/next_tick.js:176:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
lerna ERR! exec Errored while executing 'babel src --optional runtime --out-dir lib --ignore __tests__' in '@multicycles/front'
🎉  Successfully compiled 1 file with Babel.
🎉  Successfully compiled 1 file with Babel.
(node:19988) UnhandledPromiseRejectionWarning: Error: Command failed: babel src --optional runtime --out-dir lib --ignore __tests__
    at Promise.all.then.arr (D:\Sources\Node.js\multicycles\node_modules\execa\index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(node:19988) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
(node:19988) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! multicycles@1.0.0-beta.1 transpile: `lerna exec --ignore '@multicycles/{api,front,developer}' -- babel src --optional runtime --out-dir lib --ignore "__tests__"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the multicycles@1.0.0-beta.1 transpile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\raulp\AppData\Roaming\npm-cache\_logs\2018-10-03T15_10_04_053Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! multicycles@1.0.0-beta.1 prepare: `npm run clean && npm run transpile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the multicycles@1.0.0-beta.1 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\raulp\AppData\Roaming\npm-cache\_logs\2018-10-03T15_10_04_103Z-debug.log

```
