### ISSUE TITLE
Is lime login broken?

### ISSUE THREAD

**Issue by ohadcn** [PierrickP/multicycles#72]
Trying to connect my lime account to multicycle is ended up with the gui getting stuck.
the console gives the attached stacktrace:

```
0 | Error: Can't process that mutation
-- | --
1 | at new CombinedError (/app/node_modules/graphql-tools/dist/stitching/errors.js:82:28)
2 | at Object.checkResultAndHandleErrors (/app/node_modules/graphql-tools/dist/stitching/errors.js:98:15)
3 | at CheckResultAndHandleErrors.transformResult  (/app/node_modules/graphql-tools/dist/transforms/CheckResultAndHandleErrors.js:9:25)
4 | at /app/node_modules/graphql-tools/dist/transforms/transforms.js:18:54
5 | at Array.reduce (<anonymous>)
6 | at applyResultTransforms (/app/node_modules/graphql-tools/dist/transforms/transforms.js:17:23)
7 | at /app/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:97:50
8 | at step (/app/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:31:23)
9 | at Object.next (/app/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:12:53)
10 | at fulfilled (/app/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:3:58)
11 | at <anonymous>
12 | at process._tickCallback (internal/process/next_tick.js:188:7)
```

![image](https://user-images.githubusercontent.com/905635/56374857-cd007680-620c-11e9-8703-3446c36a90d3.png)

**Comment by PierrickP** [comment]
Hey, Sadly sometime, lime is rate limited.
Try 1 minutes later.
We working on something to limiting this

**Comment by ohadcn** [comment]
Lime rate limits only register / login? 
Is this per ip?

**Comment by PierrickP** [comment]
all endpoints, per accounts
